#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COMPONENTS = [
  {
    name: "text-transition",
    file: "TextTransition.tsx",
    exportName: "TextTransition",
  },
  {
    name: "backgrounds",
    file: "Backgrounds.tsx",
    exportName: "Backgrounds",
  },
  {
    name: "hero-title",
    file: "HeroTitle.tsx",
    exportName: "HeroTitle",
  },
];

const TEMPLATE_DIR = path.resolve(__dirname, "..", "templates", "components");

const toKebab = (value) =>
  value
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/\s+/g, "-")
    .toLowerCase();

const normalizeName = (value) => {
  const lower = value.toLowerCase();
  if (lower === "texttransition" || lower === "text-transition") return "text-transition";
  if (lower === "background" || lower === "backgrounds") return "backgrounds";
  if (lower === "herotitle" || lower === "hero-title") return "hero-title";
  return toKebab(value);
};

const printHelp = () => {
  console.log(`remotionbits install <components...> [--dir path] [--overwrite]
remotionbits list

Examples:
  remotionbits install text-transition hero-title
  remotionbits install all --dir src/remotionbits
  npx remotion-bits@latest install backgrounds
  bunx remotion-bits@latest install all
`);
};

const getTargetDir = (args) => {
  const dirFlagIndex = args.findIndex((arg) => arg === "--dir" || arg === "-d");
  if (dirFlagIndex !== -1 && args[dirFlagIndex + 1]) {
    return path.resolve(process.cwd(), args[dirFlagIndex + 1]);
  }
  return path.resolve(process.cwd(), "src", "remotionbits");
};

const hasOverwrite = (args) => args.includes("--overwrite");

const listComponents = () => {
  console.log("Available components:");
  for (const component of COMPONENTS) {
    console.log(`- ${component.name}`);
  }
};

const resolveComponents = (requested) => {
  if (requested.length === 0 || requested.includes("all")) {
    return COMPONENTS;
  }
  const normalized = requested.map(normalizeName);
  const selected = COMPONENTS.filter((component) =>
    normalized.includes(component.name)
  );
  const missing = normalized.filter(
    (name) => !COMPONENTS.some((component) => component.name === name)
  );
  return { selected, missing };
};

const ensureDir = async (dirPath) => {
  await fs.mkdir(dirPath, { recursive: true });
};

const copyComponent = async (component, targetDir, overwrite) => {
  const src = path.join(TEMPLATE_DIR, component.file);
  const dest = path.join(targetDir, component.file);
  try {
    await fs.access(dest);
    if (!overwrite) {
      return { status: "skipped", component };
    }
  } catch {
    // file does not exist
  }
  await fs.copyFile(src, dest);
  return { status: "installed", component };
};

const writeIndexFile = async (targetDir, components) => {
  const lines = [
    "// Generated by remotionbits",
    ...components.map(
      (component) =>
        `export { ${component.exportName} } from \"./${component.file.replace(
          /\.tsx$/,
          ""
        )}\";`
    ),
    "",
  ];
  await fs.writeFile(path.join(targetDir, "index.ts"), lines.join("\n"), "utf8");
};

const main = async () => {
  const args = process.argv.slice(2);
  const [command, ...rest] = args;

  if (!command || command === "--help" || command === "-h") {
    printHelp();
    return;
  }

  if (command === "list") {
    listComponents();
    return;
  }

  if (command !== "install") {
    console.error(`Unknown command: ${command}`);
    printHelp();
    process.exitCode = 1;
    return;
  }

  const requested = rest.filter((arg) => !arg.startsWith("-"));
  const targetDir = getTargetDir(rest);
  const overwrite = hasOverwrite(rest);

  const resolved = resolveComponents(requested);
  const selected = Array.isArray(resolved) ? resolved : resolved.selected;
  const missing = Array.isArray(resolved) ? [] : resolved.missing;

  if (missing.length > 0) {
    console.error(`Unknown components: ${missing.join(", ")}`);
    listComponents();
    process.exitCode = 1;
    return;
  }

  await ensureDir(targetDir);

  const results = [];
  for (const component of selected) {
    results.push(await copyComponent(component, targetDir, overwrite));
  }

  await writeIndexFile(targetDir, selected);

  for (const result of results) {
    const prefix = result.status === "installed" ? "✔" : "•";
    const status = result.status === "installed" ? "installed" : "skipped";
    console.log(`${prefix} ${result.component.name} (${status})`);
  }

  console.log(`\nInstalled ${selected.length} component(s) into ${targetDir}`);
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
